# -*- coding: utf-8 -*-
"""assignment 2.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1sRxHeyveh64nCHZ7ZotlKRGJnmM88MmO
"""

import pandas as pd
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# Hypothetical dataset (replace with your actual data)
data = pd.DataFrame({
    "Speeding": [1, 0, 1, 0, 1],  # Boolean: 1 = Yes, 0 = No
    "Time_of_Day": ["Night", "Day", "Night", "Day", "Night"],  # Categorical
    "Road_Condition": ["Wet", "Dry", "Wet", "Dry", "Wet"],  # Categorical
    "Severity_Index": [3, 1, 4, 2, 5]  # Numerical (example severity scale)
})

# Preprocess categorical variables (one-hot encoding)
data = pd.get_dummies(data, columns=["Time_of_Day", "Road_Condition"])

# Define dependent and independent variables
X = data[["Speeding", "Time_of_Day_Day", "Time_of_Day_Night", "Road_Condition_Dry", "Road_Condition_Wet"]]
y = data["Severity_Index"]

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

# Train the linear regression model
model = LinearRegression()
model.fit(X_train, y_train)

# Make a prediction for a new data point
new_data = [[1, 0, 1, 0, 1]]  # [Speeding, Time_of_Day_Day, Time_of_Day_Night, Road_Condition_Dry, Road_Condition_Wet]
predicted_severity = model.predict(new_data)[0]

# Print the predicted severity
print("Predicted Severity:", predicted_severity)